In [11]:
import numpy as np

In [2]:
mylist = [0,1,2,3,4]

print(mylist[1:3])

[1, 2]


In [3]:
print(mylist[:-2])

[0, 1, 2]


In [4]:
print(mylist[::-1])

[4, 3, 2, 1, 0]


In [7]:
x=[[0,1,2],[3,4,5]]
y=[[3,4,5],[6,7,8]]

x1 = np.array(x)
y1= np.array(y)

z= x1+y1

z = [[0,0,0],[0,0,0]]
for i in range(len(x)):
    for j in range(len(x[i])):
        z[i][j] = x[i][j]+y[i][j]
        
print(z)

[[3, 5, 7], [9, 11, 13]]


In [8]:
type(z)

list

In [9]:
type(x1)

numpy.ndarray

In [37]:
s = """가나나다러ㅏㄴㅇ러ㅏㅣㅇㄴ
"""
s1 ='''djkrjdklfjl
'''
print(s)

가나나다러ㅏㄴㅇ러ㅏㅣㅇㄴ



In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0,10,2)    
print(a2)                

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5) 
print(a3) 
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2,3))
print(a4.shape)

(2, 3)


In [6]:
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
a5 = np.full((2,3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [8]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
a7 = np.random.random((2,4)) 
                    # rank 2 array (2 rows 4 columns) with
                    # random values
                    # in the half-open interval [0.0, 1.0)
print(a7)

[[0.88501306 0.22274658 0.51901749 0.42577079]
 [0.3761105  0.09342529 0.19687489 0.54962704]]


In [4]:
list1 = [1,2,3,4,5]  # list1 is a list in Python
r1 = np.array(list1) # rank 1 array
print(r1)            # [1 2 3 4 5]

[1 2 3 4 5]


In [5]:
type(list1)

list

In [6]:
type(r1)

numpy.ndarray

In [11]:
print(r1[0])         # 1
print(r1[1])         # 2
list2 = [6,7,8,9,0]
r2 = np.array([list1,list2])
print(r2)            # rank 2 array
'''
[[1 2 3 4 5]
[6 7 8 9 0]] '''
print(r2.shape)      # (2,5) - 2 rows and 5 columns
print(r2[0,0])       # 1
print(r2[0,1])       # 2
print(r2[1,0])       # 6
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1[[2,4]])     # [3 5]

1
2
[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6
[3 5]


In [12]:
print(r1>2)     # [False False  True  True  True]
print(r1[r1>2])    # [3 4 5]
nums = np.arange(20)
print(nums)        # [ 0  1  2  ... 11 12 13 14 15 16 17 18 19]
odd_num = nums[nums % 2 == 1]
print(odd_num)     # [ 1  3  5  7  9 11 13 15 17 19]

[False False  True  True  True]
[3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
a = np.array([[1,2,3,4,5],
              [4,5,6,7,8],
              [9,8,7,6,5]]) # rank 2 array
print(a)
'''
[[1 2 3 4 5]
[4 5 6 7 8]
[9 8 7 6 5]] '''
b1 = a[1:3, :3]
    # row 1 to 3 (not inclusive) and first 3 columns
print(b1)
b2 = a[-2:,-2:]
print(b2)
b3 = a[1:, 2:]      # row 1 onwards and column 2 onwards
                    # b3 is now pointing to a subset of a
print(b3)
b3[0,2] = 88 # b3[0,2] is pointing to a[1,4]; modifying it will
             # modify the original array
print(a)
b4 = a[2:, :]       # row 2 onwards and all columns
print(b4)
print(b4.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
[[4 5 6]
 [9 8 7]]
[[7 8]
 [6 5]]
[[6 7 8]
 [7 6 5]]
[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]
[[9 8 7 6 5]]
(1, 5)


In [12]:
a = np.array([[1,2,3,4,5],
              [4,5,6,7,8],
              [9,8,7,6,5]]) # rank 2 array
print(a)
'''
[[1 2 3 4 5]
[4 5 6 7 8]
[9 8 7 6 5]] '''
b1 = a[1:3, :3]
    # row 1 to 3 (not inclusive) and first 3 columns
print(b1)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
[[4 5 6]
 [9 8 7]]


In [18]:
x = np.array([2,3]) 
y = np.array([4,2]) 
z = x + y
print(z)

names   = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

bmi = weights/heights **2            # calculate the BMI
print(bmi) # [ 28.88888889  14.51836889   23.046875  ]

print("Overweight: " , names[bmi>25])
# Overweight:  ['Ann']
print("Underweight: " , names[bmi<18.5])
# Underweight:  ['Joe']
print("Healthy: " , names[(bmi>=18.5) & (bmi<=25)])
# Healthy:  ['Mark']

[6 5]
[28.88888889 14.51836889 23.046875  ]
Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']


In [20]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10], [11,12]])
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


In [21]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)
'''
[[1 2 3]
[4 5 6]
[7 8 9]] '''

# Cumulative Sum
print(a.cumsum()) # prints the cumulative sum of all the
                  # elements in the array
                  # [ 1  3  6 10 15 21 28 36 45]
print(a.cumsum(axis=0))  
# sum over rows for each of the 3 columns
print(a.cumsum(axis=1))  
# sum over columns for each of the 3 rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [22]:
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages)
print(sorted_ages)
print(ages)
ages.sort()                   # modifies the array
print(ages)                   # [ 5 12 13 34 37]
ages = np.array([34,12,37,5,13])
print(ages.argsort())         # [3 1 4 0 2]

[ 5 12 13 34 37]
[34 12 37  5 13]
[ 5 12 13 34 37]
[3 1 4 0 2]


In [7]:
# Pandas stands for Panel Data Analysis.

import pandas as pd
series = pd.Series([1,2,3,4,5])
print(series)

series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series)

print(series[2])          # 3
  # same as
print(series.iloc[2])     
# 3  - based on the position of the index

print(series['d'])        # 4
    # same as
print(series.loc['d'])    
# 4 - based on the label in the index

print(series[2:])         # returns a Series
print(series.iloc[2:])    # returns a Series

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
c    5
dtype: int64
3
3
4
4
c    3
d    4
c    5
dtype: int64
c    3
d    4
c    5
dtype: int64


In [8]:
dates1 = pd.date_range('20190525', periods=12)
print(dates1)

series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
series.index = dates1
print(series)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[ns]', freq='D')
2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64


In [9]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,4),
                columns=list('ABCD'))
print(df)

df.to_csv('data.csv', index=False)

          A         B         C         D
0 -1.580880  0.356512  1.347830  0.420711
1 -3.039650 -1.161323  0.024068 -1.751626
2  0.029008  1.170472  0.701966  0.165582
3  1.524562 -0.932944 -0.222846 -1.330724
4  0.007992  0.202968  1.440372 -0.240814
5  0.069716 -1.905796 -1.381472  0.476243
6 -1.867213 -1.100507  0.485470  1.955429
7 -0.677773 -1.146159  1.762654  0.129031
8  0.203841 -0.024464 -0.575576 -1.972606
9 -0.741636 -1.837317  1.942517  0.292937


In [10]:
df = pd.read_csv('data.csv')
days = pd.date_range('20190525', periods=10)
df.index = days
print(df)
print(df.index)
print(df.values)

                   A         B         C         D
2019-05-25 -1.580880  0.356512  1.347830  0.420711
2019-05-26 -3.039650 -1.161323  0.024068 -1.751626
2019-05-27  0.029008  1.170472  0.701966  0.165582
2019-05-28  1.524562 -0.932944 -0.222846 -1.330724
2019-05-29  0.007992  0.202968  1.440372 -0.240814
2019-05-30  0.069716 -1.905796 -1.381472  0.476243
2019-05-31 -1.867213 -1.100507  0.485470  1.955429
2019-06-01 -0.677773 -1.146159  1.762654  0.129031
2019-06-02  0.203841 -0.024464 -0.575576 -1.972606
2019-06-03 -0.741636 -1.837317  1.942517  0.292937
DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03'],
              dtype='datetime64[ns]', freq='D')
[[-1.58087973  0.35651203  1.3478299   0.42071083]
 [-3.03964995 -1.1613232   0.02406812 -1.75162593]
 [ 0.02900801  1.17047212  0.70196622  0.16558186]
 [ 1.52456158 -0.93294355 -0.22284558 -1.33072447]
 

In [11]:
print(df.describe())
print(df.mean(0))    
# 0 means compute the mean for each columns
print(df.mean(1))   # 1 means compute the mean for each row
print(df.head())
print(df.tail())

print(df['A'])
# same as
print(df.A)

print(df[['A', 'B']])
print(df[2:4])
print(df.iloc[2:4])

print(df[(df.A > 0) & (df.B>0)])

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.607203  -0.637856   0.552498  -0.185584
std     1.287512   1.012255   1.092272   1.192624
min    -3.039650  -1.905796  -1.381472  -1.972606
25%    -1.371069  -1.157532  -0.161117  -1.058247
50%    -0.334890  -1.016725   0.593718   0.147307
75%     0.059539   0.146110   1.417236   0.388767
max     1.524562   1.170472   1.942517   1.955429
A   -0.607203
B   -0.637856
C    0.552498
D   -0.185584
dtype: float64
2019-05-25    0.136043
2019-05-26   -1.482133
2019-05-27    0.516757
2019-05-28   -0.240488
2019-05-29    0.352630
2019-05-30   -0.685327
2019-05-31   -0.131705
2019-06-01    0.016938
2019-06-02   -0.592202
2019-06-03   -0.085875
Freq: D, dtype: float64
                   A         B         C         D
2019-05-25 -1.580880  0.356512  1.347830  0.420711
2019-05-26 -3.039650 -1.161323  0.024068 -1.751626
2019-05-27  0.029008  1.170472  0.701966  0.165582
2019-05-28  1.524562 

In [12]:
print(df[['A', 'B']])
print(df[2:4])
print(df.iloc[2:4])

                   A         B
2019-05-25 -1.580880  0.356512
2019-05-26 -3.039650 -1.161323
2019-05-27  0.029008  1.170472
2019-05-28  1.524562 -0.932944
2019-05-29  0.007992  0.202968
2019-05-30  0.069716 -1.905796
2019-05-31 -1.867213 -1.100507
2019-06-01 -0.677773 -1.146159
2019-06-02  0.203841 -0.024464
2019-06-03 -0.741636 -1.837317
                   A         B         C         D
2019-05-27  0.029008  1.170472  0.701966  0.165582
2019-05-28  1.524562 -0.932944 -0.222846 -1.330724
                   A         B         C         D
2019-05-27  0.029008  1.170472  0.701966  0.165582
2019-05-28  1.524562 -0.932944 -0.222846 -1.330724


In [35]:
import pandas as pd
data = {'name': ['Janet', 'Nad', 'Timothy', 'June', 'Amy'],
      'year': [2012, 2012, 2013, 2014, 2014],
      'reports': [6, 13, 14, 1, 7]}
df = pd.DataFrame(data, index =
     ['Singapore', 'China', 'Japan', 'Sweden', 'Norway'])
print(df)

import numpy as np
schools = np.array(["Cambridge","Oxford","Oxford","Cambridge",
                    "Oxford"])
df["school"] = schools
print(df)

print(df.drop(['China', 'Japan'])) 
# drop rows based on value of index
print(df[df.name != 'Nad']) # drop row based on column value

print(df.drop('reports', axis=1))   # drop column


              name  year  reports
Singapore    Janet  2012        6
China          Nad  2012       13
Japan      Timothy  2013       14
Sweden        June  2014        1
Norway         Amy  2014        7
              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford
            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford


In [36]:
df = pd.DataFrame(
      {
          "Gender": ['Male','Male','Female','Female','Female'],
          "Team"  : [1,2,3,3,1]
      })
print(df)

print("Displaying the distribution of genders in each team")
print(pd.crosstab(df.Gender, df.Team))

print(pd.crosstab(df.Team, df.Gender))

   Gender  Team
0    Male     1
1    Male     2
2  Female     3
3  Female     3
4  Female     1
Displaying the distribution of genders in each team
Team    1  2  3
Gender         
Female  1  0  2
Male    1  1  0
Gender  Female  Male
Team                
1            1     1
2            0     1
3            2     0


In [1]:
import re

re.search("(\w+)", "wow, it is awesom")

<re.Match object; span=(0, 3), match='wow'>

In [2]:
re.split("(\w+)", "wow, it is world of word")

['', 'wow', ', ', 'it', ' ', 'is', ' ', 'world', ' ', 'of', ' ', 'word', '']

In [3]:
re.sub("\d", "number", "7 candy")

'number candy'

In [4]:
re.findall("(\w+)", "wow, it is awesom")

['wow', 'it', 'is', 'awesom']

In [6]:
arr = range(10)

In [7]:
type(arr)

range

In [8]:
print(arr)

range(0, 10)


In [9]:
list(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]